### ISSUE TITLE
Interface auto-scaling ratio

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [arx-insanity/ArxLibertatis#28]
- [ ] Interface proper auto-scaling with high resolution textures for HUD and books, make bigger images look like they are normal sized in vanilla, including character sheets, books, notes, public notices, spell- and misc icons.
- [ ] Make the auto scaling work properly using different resolutions and screen ratios
- [ ] When we get gold or sheet updates, screen icons as gold bag and book will glow with a halo, fix the size of the halo.

**Comment by Gussak** [comment]
is this about the char_sheet_book.bmp 2052 × 1252 (and others) of insanity mod Arx_Insanity_Demo_v0.4.71_Complete being too large to fit a screen resolution of 1366x768?  
I tested overriding it with the small 513 × 313, and it looks good now.  
I think the big one needs auto downscaling on the code right?
